# Site settings
baseurl = "http://adolfosbh.github.io/"
languageCode = "en-en"
title = "Adolfo SBH"
theme = "artists"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Adolfo Sánchez-Barbudo Herrera"
	description = "Personal web site of Adolfo Sánchez-Barbudo Herrera"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "me@[first-name]sbh.co"


	# Header an navigation
	#
	# To change the header background the 'hero-bg-jpg' at 'static/img'.
	# Do the same with the logo ('logo.svg').
	# But keep the original filename!
	[params.header]
		title = "Adolfo SBH"
		shortBio = "Software Engineer | Model-Driven Engineering Passionate"


	# About section
	#
	# Replace the 'avatar.jpg' under 'static/img' with your own image.
	[params.about]
		title = "About me"
		bio = "Welcome to my personal web site. No, I don't track any data from you (no need for numbers or demographics). Here, you will probably find all what you need to know about me, otherwise drop me an email ;). As a short bio, I prefer to see my life as a list of goals that I've been able to achieve so far (chronologically): MSc in Computer Science (credited with best academic transcripts), committer of open source projects in a transparent, open and wide software community ([Eclipse](https://eclipse.org)), contributor of standardized and open specifications ([Object Management Group](https://omg.org)), author and presenter of several works at international venues, founder and CTO of an unsuccessful start-up, author of a book chapter about [MDE](http://www.ra-ma.es/libros/DESARROLLO-DE-SOFTWARE-DIRIGIDO-POR-MODELOS-CONCEPTOS-METODOS-Y-HERRAMIENTAS/82019/978-84-9964-215-4), married and father of a lovely child, Doctorate of Engineering ([University of York](http://etheses.whiterose.ac.uk/17416/)). I've recently passed a selective opposition to be member of the superior corpse responsible for the IT systems of the Spanish State Administration."

    [[params.about.skills]]
      name = "Programming"
      value = 9
    [[params.about.skills]]
      name = "Web Design"
      value = 4
    [[params.about.skills]]
      name = "Learning"
      value = 10
    [[params.about.skills]]
        name = "Planning"
        value = 8
	[[params.about.skills]]
		name = "Communication"
		value = 7
    [[params.about.skills]]
        name = "Innovation"
        value = 9

	# Contact secion
	[params.contact]
		title = "Contact"

		# The following social network icons are available:
		# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
		# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
		[[params.contact.social]]
			icon = "twitter"
			link = "//twitter.com/adolfosbh"

		[[params.contact.social]]
			icon = "github"
			link = "//github.com/adolfosbh"

		[[params.contact.social]]
			icon = "linkedin"
			link = "//www.linkedin.com/in/adolfosbh"


#	[params.form]
#		title = "Let's work together"
		# Form fields
#		name = "Your Name"
#		email = "Your Email"
#		message = "Tell me about your project"
#		buttonText = "Send"

	[params.clients]
		title = "References"
		
	[params.footer]
		copyright = "Site powered by [Hugo](http://gohugo.io) and [Artists](http://themes.gohugo.io/theme/artists/) theme"
